# Generated by Django 5.1.1 on 2024-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_rename_like_productlike_commentaction_reviewaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaction',
            name='action',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'dislike')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='action',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'dislike')], max_length=10, null=True),
        ),
    ]
