# Generated by Django 5.1.1 on 2024-09-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_commentaction_action_alter_reviewaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaction',
            name='action',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='action',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'dislike')], max_length=10),
        ),
    ]
