# Generated by Django 5.1.1 on 2024-09-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_commentaction_action_alter_reviewaction_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaction',
            old_name='action',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='reviewaction',
            old_name='action',
            new_name='action_type',
        ),
    ]
