openapi: 3.0.3
info:
  title: Django DRF ECOMMERCE API
  version: 3.0.3
paths:
  /brands/:
    get:
      operationId: brands_retrieve
      tags:
        - brands
      security:
        - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: brands_create
      tags:
        - brands
      security:
        - jwtAuth: []
      responses:
        '201':
          description: No response body
  /brands/{id}/:
    get:
      operationId: brands_retrieve_2
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      tags:
        - brands
      security:
        - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: brands_update
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      tags:
        - brands
      security:
        - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/add_to_cart/{id}/:
    get:
      operationId: cart_add_to_cart_retrieve
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      tags:
        - cart
      security:
        - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: cart_add_to_cart_create
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      tags:
        - cart
      security:
        - jwtAuth: []
      responses:
        '200':
          description: No response body
  # Continue this pattern for all your paths
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
