# Generated by Django 5.1.1 on 2024-10-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_alter_coupon_is_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='reserve_id',
        ),
    ]
